sudo: required
services:
  - docker

before_install:
  - docker build -t hebbaruday/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hebbaruday/react-test npm run test -- --coverage
after_success:
 - docker build -t hebbaruday/multi-client ./client
 - docker build -t hebbaruday/multi-nginx ./nginx
 - docker build -t hebbaruday/multi-server ./server
 - docker build -t hebbaruday/multi-wroker ./worker

# log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push hebbaruday/multi-client
 - docker push hebbaruday/multi-nginx
 - docker push hebbaruday/multi-server
 - docker push hebbaruday/multi-wroker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-900079224734"
  bucket_path: "docker"
  on:
    branch: master      
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY