sudo: required
services:
  - docker

before_install:
  - docker build -t uday/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true uday/react-test npm run test -- --coverage
after_success:
 - docker build -t uday/multi-client ./client
 - docker build -t uday/multi-nginx ./nginx
 - docker build -t uday/multi-server ./server
 - docker build -t uday/multi-wroker ./worker

# log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push uday/multi-client
 - docker push uday/multi-nginx
 - docker push uday/multi-server
 - docker push uday/multi-wroker

